@Library("jenlib") _

wafDefaultPipeline(projects: ["hxcomm"],
                   container: [app: "visionary-dls"],
                   testSlurmResource: [partition: "cube", gres: "cube1", licenses: "W4F3"],
                   testOptions: "--test-execall -j1",
                   notificationChannel: "#dls-software",
                   warningsIgnorePattern: "*/lib-rcf/*")
