@Library("jenlib") _

wafDefaultPipeline(projects: ["hxcomm"],
                   container: [app: "dls-core"],
                   testSlurmResource: [partition: "cube", wafer: 62, "fpga-without-aout": 3],
                   testOptions: "--test-execall -j1",
                   notificationChannel: "#dls-software")
