@Library("jenlib@ebrains-6.0") _

Map<String, Object> pipelineOptions = [
		projects: ["hxcomm"],
		setupOptions: "--release-branch=ebrains-6.0",
		container: [app: "dls-core", singularityArgs: "-B /run/munge"],
		notificationChannel: "#dls-software",
		configureInstallOptions: "--build-profile=ci"
]

if (!isTriggeredByGerrit()) {
	pipelineOptions << [
			testSlurmResource: getHxTestResource(3) << ["mem": 30000],
			preTestHook: { configureHxCubeBitfile() },
			testOptions: "--test-execall -j1",
	]
}

withCcache() {
	wafDefaultPipeline(pipelineOptions)
}
